syntax = "proto3";

package gophkeeper.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/a-aleesshin/gophkeeper/api/proto/gophkeeper/v1;gophkeeperv1";

service AccessService {
  rpc Login(LoginRequest) returns (TokenPair);
  rpc Refresh(RefreshRequest) returns (TokenPair);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
}

message LoginRequest {
  string login = 1;
  string password = 2;
}

message TokenPair {
  string access_token = 1;
  google.protobuf.Timestamp access_expires_at = 2;
  string refresh_token = 3;
  google.protobuf.Timestamp refresh_expires_at = 4;
}

message RefreshRequest {
  string refresh_token = 1;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {}
