// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: gophkeeper/v1/vault.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED SecretType = 0
	SecretType_SECRET_TYPE_CREDENTIALS SecretType = 1
	SecretType_SECRET_TYPE_TEXT        SecretType = 2
	SecretType_SECRET_TYPE_BINARY      SecretType = 3
	SecretType_SECRET_TYPE_CARD        SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_CREDENTIALS",
		2: "SECRET_TYPE_TEXT",
		3: "SECRET_TYPE_BINARY",
		4: "SECRET_TYPE_CARD",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED": 0,
		"SECRET_TYPE_CREDENTIALS": 1,
		"SECRET_TYPE_TEXT":        2,
		"SECRET_TYPE_BINARY":      3,
		"SECRET_TYPE_CARD":        4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_vault_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_vault_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{0}
}

type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *CreateSecretRequest) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateSecretRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSecretResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretResponse) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *GetSecretResponse) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *GetSecretResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetSecretResponse) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetSecretResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetSecretResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetSecretResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{4}
}

type SecretHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretHeader) Reset() {
	*x = SecretHeader{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretHeader) ProtoMessage() {}

func (x *SecretHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretHeader.ProtoReflect.Descriptor instead.
func (*SecretHeader) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{5}
}

func (x *SecretHeader) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SecretHeader) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretHeader) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SecretHeader) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretHeader) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SecretHeader        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{6}
}

func (x *ListSecretsResponse) GetItems() []*SecretHeader {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *UpdateSecretRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateSecretRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateSecretRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSecretResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *DeleteSecretRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSecretResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SyncItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	BaseVersion   int64                  `protobuf:"varint,6,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncItem) Reset() {
	*x = SyncItem{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncItem) ProtoMessage() {}

func (x *SyncItem) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncItem.ProtoReflect.Descriptor instead.
func (*SyncItem) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{11}
}

func (x *SyncItem) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SyncItem) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SyncItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncItem) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SyncItem) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *SyncItem) GetBaseVersion() int64 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

type SyncSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Items         []*SyncItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSecretsRequest) Reset() {
	*x = SyncSecretsRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSecretsRequest) ProtoMessage() {}

func (x *SyncSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSecretsRequest.ProtoReflect.Descriptor instead.
func (*SyncSecretsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{12}
}

func (x *SyncSecretsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *SyncSecretsRequest) GetItems() []*SyncItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SyncApplied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncApplied) Reset() {
	*x = SyncApplied{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncApplied) ProtoMessage() {}

func (x *SyncApplied) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncApplied.ProtoReflect.Descriptor instead.
func (*SyncApplied) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{13}
}

func (x *SyncApplied) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SyncApplied) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SyncConflict struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SecretId       string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	ServerType     SecretType             `protobuf:"varint,2,opt,name=server_type,json=serverType,proto3,enum=gophkeeper.v1.SecretType" json:"server_type,omitempty"`
	ServerPayload  []byte                 `protobuf:"bytes,3,opt,name=server_payload,json=serverPayload,proto3" json:"server_payload,omitempty"`
	ServerMetadata []byte                 `protobuf:"bytes,4,opt,name=server_metadata,json=serverMetadata,proto3" json:"server_metadata,omitempty"`
	ServerDeleted  bool                   `protobuf:"varint,5,opt,name=server_deleted,json=serverDeleted,proto3" json:"server_deleted,omitempty"`
	ServerVersion  int64                  `protobuf:"varint,6,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncConflict) Reset() {
	*x = SyncConflict{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConflict) ProtoMessage() {}

func (x *SyncConflict) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConflict.ProtoReflect.Descriptor instead.
func (*SyncConflict) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{14}
}

func (x *SyncConflict) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SyncConflict) GetServerType() SecretType {
	if x != nil {
		return x.ServerType
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SyncConflict) GetServerPayload() []byte {
	if x != nil {
		return x.ServerPayload
	}
	return nil
}

func (x *SyncConflict) GetServerMetadata() []byte {
	if x != nil {
		return x.ServerMetadata
	}
	return nil
}

func (x *SyncConflict) GetServerDeleted() bool {
	if x != nil {
		return x.ServerDeleted
	}
	return false
}

func (x *SyncConflict) GetServerVersion() int64 {
	if x != nil {
		return x.ServerVersion
	}
	return 0
}

func (x *SyncConflict) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SyncChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChange) Reset() {
	*x = SyncChange{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChange) ProtoMessage() {}

func (x *SyncChange) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChange.ProtoReflect.Descriptor instead.
func (*SyncChange) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{15}
}

func (x *SyncChange) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SyncChange) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SyncChange) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncChange) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SyncChange) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *SyncChange) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SyncChange) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SyncSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       []*SyncApplied         `protobuf:"bytes,1,rep,name=applied,proto3" json:"applied,omitempty"`
	Conflicts     []*SyncConflict        `protobuf:"bytes,2,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Changes       []*SyncChange          `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	Cursor        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSecretsResponse) Reset() {
	*x = SyncSecretsResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSecretsResponse) ProtoMessage() {}

func (x *SyncSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSecretsResponse.ProtoReflect.Descriptor instead.
func (*SyncSecretsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_vault_proto_rawDescGZIP(), []int{16}
}

func (x *SyncSecretsResponse) GetApplied() []*SyncApplied {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *SyncSecretsResponse) GetConflicts() []*SyncConflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *SyncSecretsResponse) GetChanges() []*SyncChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *SyncSecretsResponse) GetCursor() *timestamppb.Timestamp {
	if x != nil {
		return x.Cursor
	}
	return nil
}

var File_gophkeeper_v1_vault_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_vault_proto_rawDesc = "" +
	"\n" +
	"\x19gophkeeper/v1/vault.proto\x12\rgophkeeper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n" +
	"\x13CreateSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\"0\n" +
	"\x14CreateSecretResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"/\n" +
	"\x10GetSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"\xa5\x02\n" +
	"\x11GetSecretResponse\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x14\n" +
	"\x12ListSecretsRequest\"\xcb\x01\n" +
	"\fSecretHeader\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadata\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"H\n" +
	"\x13ListSecretsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.gophkeeper.v1.SecretHeaderR\x05items\"\x82\x01\n" +
	"\x13UpdateSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadata\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"0\n" +
	"\x14UpdateSecretResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"L\n" +
	"\x13DeleteSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"0\n" +
	"\x14DeleteSecretResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"\xc9\x01\n" +
	"\bSyncItem\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12!\n" +
	"\fbase_version\x18\x06 \x01(\x03R\vbaseVersion\"u\n" +
	"\x12SyncSecretsRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.gophkeeper.v1.SyncItemR\x05items\"D\n" +
	"\vSyncApplied\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\xc0\x02\n" +
	"\fSyncConflict\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12:\n" +
	"\vserver_type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\n" +
	"serverType\x12%\n" +
	"\x0eserver_payload\x18\x03 \x01(\fR\rserverPayload\x12'\n" +
	"\x0fserver_metadata\x18\x04 \x01(\fR\x0eserverMetadata\x12%\n" +
	"\x0eserver_deleted\x18\x05 \x01(\bR\rserverDeleted\x12%\n" +
	"\x0eserver_version\x18\x06 \x01(\x03R\rserverVersion\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfd\x01\n" +
	"\n" +
	"SyncChange\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xef\x01\n" +
	"\x13SyncSecretsResponse\x124\n" +
	"\aapplied\x18\x01 \x03(\v2\x1a.gophkeeper.v1.SyncAppliedR\aapplied\x129\n" +
	"\tconflicts\x18\x02 \x03(\v2\x1b.gophkeeper.v1.SyncConflictR\tconflicts\x123\n" +
	"\achanges\x18\x03 \x03(\v2\x19.gophkeeper.v1.SyncChangeR\achanges\x122\n" +
	"\x06cursor\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06cursor*\x8a\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SECRET_TYPE_CREDENTIALS\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x02\x12\x16\n" +
	"\x12SECRET_TYPE_BINARY\x10\x03\x12\x14\n" +
	"\x10SECRET_TYPE_CARD\x10\x042\x95\x04\n" +
	"\fVaultService\x12W\n" +
	"\fCreateSecret\x12\".gophkeeper.v1.CreateSecretRequest\x1a#.gophkeeper.v1.CreateSecretResponse\x12N\n" +
	"\tGetSecret\x12\x1f.gophkeeper.v1.GetSecretRequest\x1a .gophkeeper.v1.GetSecretResponse\x12T\n" +
	"\vListSecrets\x12!.gophkeeper.v1.ListSecretsRequest\x1a\".gophkeeper.v1.ListSecretsResponse\x12W\n" +
	"\fUpdateSecret\x12\".gophkeeper.v1.UpdateSecretRequest\x1a#.gophkeeper.v1.UpdateSecretResponse\x12W\n" +
	"\fDeleteSecret\x12\".gophkeeper.v1.DeleteSecretRequest\x1a#.gophkeeper.v1.DeleteSecretResponse\x12T\n" +
	"\vSyncSecrets\x12!.gophkeeper.v1.SyncSecretsRequest\x1a\".gophkeeper.v1.SyncSecretsResponseBHZFgithub.com/a-aleesshin/gophkeeper/api/proto/gophkeeper/v1;gophkeeperv1b\x06proto3"

var (
	file_gophkeeper_v1_vault_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_vault_proto_rawDescData []byte
)

func file_gophkeeper_v1_vault_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_vault_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_vault_proto_rawDesc), len(file_gophkeeper_v1_vault_proto_rawDesc)))
	})
	return file_gophkeeper_v1_vault_proto_rawDescData
}

var file_gophkeeper_v1_vault_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_v1_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_gophkeeper_v1_vault_proto_goTypes = []any{
	(SecretType)(0),               // 0: gophkeeper.v1.SecretType
	(*CreateSecretRequest)(nil),   // 1: gophkeeper.v1.CreateSecretRequest
	(*CreateSecretResponse)(nil),  // 2: gophkeeper.v1.CreateSecretResponse
	(*GetSecretRequest)(nil),      // 3: gophkeeper.v1.GetSecretRequest
	(*GetSecretResponse)(nil),     // 4: gophkeeper.v1.GetSecretResponse
	(*ListSecretsRequest)(nil),    // 5: gophkeeper.v1.ListSecretsRequest
	(*SecretHeader)(nil),          // 6: gophkeeper.v1.SecretHeader
	(*ListSecretsResponse)(nil),   // 7: gophkeeper.v1.ListSecretsResponse
	(*UpdateSecretRequest)(nil),   // 8: gophkeeper.v1.UpdateSecretRequest
	(*UpdateSecretResponse)(nil),  // 9: gophkeeper.v1.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),   // 10: gophkeeper.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),  // 11: gophkeeper.v1.DeleteSecretResponse
	(*SyncItem)(nil),              // 12: gophkeeper.v1.SyncItem
	(*SyncSecretsRequest)(nil),    // 13: gophkeeper.v1.SyncSecretsRequest
	(*SyncApplied)(nil),           // 14: gophkeeper.v1.SyncApplied
	(*SyncConflict)(nil),          // 15: gophkeeper.v1.SyncConflict
	(*SyncChange)(nil),            // 16: gophkeeper.v1.SyncChange
	(*SyncSecretsResponse)(nil),   // 17: gophkeeper.v1.SyncSecretsResponse
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_gophkeeper_v1_vault_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.CreateSecretRequest.type:type_name -> gophkeeper.v1.SecretType
	0,  // 1: gophkeeper.v1.GetSecretResponse.type:type_name -> gophkeeper.v1.SecretType
	18, // 2: gophkeeper.v1.GetSecretResponse.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: gophkeeper.v1.GetSecretResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: gophkeeper.v1.SecretHeader.type:type_name -> gophkeeper.v1.SecretType
	18, // 5: gophkeeper.v1.SecretHeader.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 6: gophkeeper.v1.ListSecretsResponse.items:type_name -> gophkeeper.v1.SecretHeader
	0,  // 7: gophkeeper.v1.SyncItem.type:type_name -> gophkeeper.v1.SecretType
	18, // 8: gophkeeper.v1.SyncSecretsRequest.since:type_name -> google.protobuf.Timestamp
	12, // 9: gophkeeper.v1.SyncSecretsRequest.items:type_name -> gophkeeper.v1.SyncItem
	0,  // 10: gophkeeper.v1.SyncConflict.server_type:type_name -> gophkeeper.v1.SecretType
	18, // 11: gophkeeper.v1.SyncConflict.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 12: gophkeeper.v1.SyncChange.type:type_name -> gophkeeper.v1.SecretType
	18, // 13: gophkeeper.v1.SyncChange.updated_at:type_name -> google.protobuf.Timestamp
	14, // 14: gophkeeper.v1.SyncSecretsResponse.applied:type_name -> gophkeeper.v1.SyncApplied
	15, // 15: gophkeeper.v1.SyncSecretsResponse.conflicts:type_name -> gophkeeper.v1.SyncConflict
	16, // 16: gophkeeper.v1.SyncSecretsResponse.changes:type_name -> gophkeeper.v1.SyncChange
	18, // 17: gophkeeper.v1.SyncSecretsResponse.cursor:type_name -> google.protobuf.Timestamp
	1,  // 18: gophkeeper.v1.VaultService.CreateSecret:input_type -> gophkeeper.v1.CreateSecretRequest
	3,  // 19: gophkeeper.v1.VaultService.GetSecret:input_type -> gophkeeper.v1.GetSecretRequest
	5,  // 20: gophkeeper.v1.VaultService.ListSecrets:input_type -> gophkeeper.v1.ListSecretsRequest
	8,  // 21: gophkeeper.v1.VaultService.UpdateSecret:input_type -> gophkeeper.v1.UpdateSecretRequest
	10, // 22: gophkeeper.v1.VaultService.DeleteSecret:input_type -> gophkeeper.v1.DeleteSecretRequest
	13, // 23: gophkeeper.v1.VaultService.SyncSecrets:input_type -> gophkeeper.v1.SyncSecretsRequest
	2,  // 24: gophkeeper.v1.VaultService.CreateSecret:output_type -> gophkeeper.v1.CreateSecretResponse
	4,  // 25: gophkeeper.v1.VaultService.GetSecret:output_type -> gophkeeper.v1.GetSecretResponse
	7,  // 26: gophkeeper.v1.VaultService.ListSecrets:output_type -> gophkeeper.v1.ListSecretsResponse
	9,  // 27: gophkeeper.v1.VaultService.UpdateSecret:output_type -> gophkeeper.v1.UpdateSecretResponse
	11, // 28: gophkeeper.v1.VaultService.DeleteSecret:output_type -> gophkeeper.v1.DeleteSecretResponse
	17, // 29: gophkeeper.v1.VaultService.SyncSecrets:output_type -> gophkeeper.v1.SyncSecretsResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_vault_proto_init() }
func file_gophkeeper_v1_vault_proto_init() {
	if File_gophkeeper_v1_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_vault_proto_rawDesc), len(file_gophkeeper_v1_vault_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_v1_vault_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_vault_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_vault_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_vault_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_vault_proto = out.File
	file_gophkeeper_v1_vault_proto_goTypes = nil
	file_gophkeeper_v1_vault_proto_depIdxs = nil
}
